### ISSUE TITLE
docker-angular-filemanager not working anymore

### ISSUE THREAD

**Issue by marcwaz** [elboletaire/docker-angular-filemanager#1]
Hello,
angular-filemanager has been updated. As a consequence, your docker image is not working anymore.
Could you please update it ? I have tried to update it myself, but when I run it with php-local, I'm unable to have access to my local files.
Marc

**Comment by elboletaire** [comment]
Sorry for the big delay. Unfortunately I'm not gonna maintain this project anymore; I created it in a moment where I couldn't find any easy & fast file manager to be used with docker, but this has changed as there are file managers which already have their own official docker images, like [filebrowser](http://filebrowser.xyz).
